name: Docker build

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-job:
    runs-on: docker
    steps:
      - name: Checkout actions
        uses: actions/checkout@master
        
  build-job:
    runs-on: docker
    container:
      image: gcr.io/kaniko-project/executor:debug
    
    steps:
      - name: Kaniko build
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_CONTEXT
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"${{ secrets.YC_CR_ID }}\":{\"auth\":\"$(echo -n "json_key:${{ secrets.YC_CR_PASSWORD }}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
          /kaniko/executor --context $GITHUB_WORKSPACE --dockerfile "$GITHUB_WORKSPACE/Dockerfile" --destination "${{ secrets.YC_CR_ID }}/catgpt:${{ vars.GITHUB_ACTOR_ID }}"
          
