name: Docker build

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - name: Checkout actions
        uses: actions/checkout@master

      - name: Kaniko build
        uses: docker://gcr.io/kaniko-project/executor:debug
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"${{ secrets.YC_CR_ID }}\":{\"auth\":\"$(echo -n "json_key:${{ secrets.YC_CR_PASSWORD }}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
          /kaniko/executor --context ${{ vars.GITHUB_WORKSPACE }} --dockerfile "${{ vars.GITHUB_WORKSPACE }}/Dockerfile" --destination "secrets.YC_CR_ID/catgpt:${{ vars.GITHUB_ACTOR_ID }}
          
