name: Docker build
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: cr.yandex
          image: ${{ secrets.YC_REPO }}/yy/catgpt
          username: ${{ secrets.YC_CR_USERNAME }}
          password: ${{ secrets.YC_CR_PASSWORD }}
          tag: ${{ GITHUB_ACTOR_ID }}
          path: .
          #cache: true
          #cache_registry: ${{ secrets.YC_REPO }}/yy/catgpt
